name: RamBar
options:
  bundleIdPrefix: com.sihan
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
targets:
  RamBar:
    type: application
    platform: macOS
    sources:
      - path: RamBar
    settings:
      base:
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.sihan.rambar
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: RamBar/Info.plist
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
  RamBarTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: RamBarTests
    dependencies:
      - target: RamBar
    settings:
      base:
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: "YES"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
